[package]
name = "oving6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
sha = "1.0.3"
tokio = { version = "1.25.0", features = ["rt", "net", "io-util", "full"] }
